### PR TITLE
added grad progress page

### PR DESCRIPTION
**Pull request by angelahuangg**
sorry about the ugly homepage changes-- it only adds a button for the grad progress page.

### CODE REVIEW

**Review by danknessdra — APPROVED** [review]
LGTM, what are the homepage.jsp changes?

**Comment by angelahuangg** [comment]
> LGTM, what are the homepage.jsp changes?

button on the top leading to grad progress page!

**Comment by ThrawnOfAsgard** [comment]
Why is there a new interested courses table?
Wouldn't it be easier to add another column to usercourses with a boolean/tinyint to mark added/planned (0) vs completed (1)?
Then, courses added on "Search and Add" would go to usercourses table, and in the user's homepage, the user could mark the course as completed.

**Comment by angelahuangg** [comment]
> Why is there a new interested courses table? Wouldn't it be easier to add another column to usercourses with a boolean/tinyint to mark added/planned (0) vs completed (1)? Then, courses added on "Search and Add" would go to usercourses table, and in the user's homepage, the user could mark the course as completed.

Sure, that would work, but as far as I'm aware, there currently isn't a functionality to mark the courses as completed on the home page and there isn't much time to implement it either. I assume the current functionality of search and add simply marks as completed?
I'm willing to remove the interested section altogether if that is what works best with the time we have.

**Pull request merged**
